language: php
php:
  - 5.4
  - 5.3
  - hhvm
before_script:
  - composer install --dev --dev --prefer-source --no-interaction
script:
  - sudo vendor/bin/phpunit --coverage-text || ([[ $? = 139 ]] && echo && echo "Ignoring SEGFAULT.." >&2)
